behaviors:

  # SoccerTwos:
  #   trainer_type: poca
  #   hyperparameters:
  #     batch_size: 2048
  #     buffer_size: 20480
  #     learning_rate: 0.0003
  #     beta: 0.005
  #     epsilon: 0.2
  #     lambd: 0.95
  #     num_epoch: 3
  #     learning_rate_schedule: linear
  #     beta_schedule: linear
  #     epsilon_schedule: linear
  #     learning_rate_schedule: constant
  #   network_settings:
  #     normalize: false
  #     hidden_units: 512
  #     num_layers: 2
  #     vis_encode_type: simple
  #     memory: null
  #     goal_conditioning_type: hyper
  #     deterministic: false
  #   reward_signals:
  #     extrinsic:
  #       gamma: 0.99
  #       strength: 1.0
  #       network_settings:
  #         normalize: false
  #         hidden_units: 128
  #         num_layers: 2
  #         vis_encode_type: simple
  #         memory: null
  #         goal_conditioning_type: hyper
  #         deterministic: false
  #   keep_checkpoints: 5
  #   max_steps: 50000000
  #   time_horizon: 1000
  #   summary_freq: 10000
  #   self_play:
  #     save_steps: 50000
  #     team_change: 10_000_000
  #     swap_steps: 2000
  #     window: 10
  #     play_against_latest_model_ratio: 0.5
  #     initial_elo: 1200.0

  #   init_path: "./results/Base/SoccerTwos.onnx"

  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: false
    self_play:
      save_steps: 100000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
    init_path: ".//atorre_poca-SoccerTwos-100M/SoccerTwos/SoccerTwos-100000002.onnx"



    # trainer_type: poca
    # hyperparameters:
    #   batch_size: 4096
    #   buffer_size: 40960
    #   learning_rate: 0.0012
    #   beta: 0.005
    #   epsilon: 0.2
    #   lambd: 0.95
    #   num_epoch: 3
    #   learning_rate_schedule: linear
    #   beta_schedule: linear
    #   epsilon_schedule: linear
    # checkpoint_interval: 500000
    # network_settings:
    #   normalize: false
    #   hidden_units: 512
    #   num_layers: 2
    #   vis_encode_type: resnet
    #   memory: null
    #   goal_conditioning_type: hyper
    #   deterministic: false
    # reward_signals:
    #   extrinsic:
    #     gamma: 0.99
    #     strength: 1.0
    #     network_settings:
    #       normalize: false
    #       hidden_units: 128
    #       num_layers: 2
    #       vis_encode_type: simple
    #       memory: null
    #       goal_conditioning_type: hyper
    #       deterministic: false

    # # init_path: "./opponents/dfm794_poca-SoccerTwos-2x-2-r-l/SoccerTwos.onnx"

    # keep_checkpoints: 20
    # even_checkpoints: false
    # max_steps: 100000000
    # time_horizon: 1000
    # summary_freq: 10000
    # threaded: false
    # self_play:
    #   save_steps: 50000
    #   team_change: 10_000_000
    #   swap_steps: 2000
    #   window: 10
    #   play_against_latest_model_ratio: 0.5
    #   initial_elo: 1200.0
    # behavioral_cloning: null
